events {}

http {
  upstream notification_cluster {
    server notification1:3000;
    server notification2:3000;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://notification_cluster;
    }
  }
}